### ISSUE TITLE
Error when start sample server?

### ISSUE THREAD

**Issue by takaaptech** [gamestdio/colyseus.lua#1]
When i try to start server via npm start or node index.js, it throws error:

colyseus.lua-master/server/chat_room.js:3
class ChatRoom extends Room {
^^^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:404:25)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/macbook/Corona/colyseus.lua-master/server/index.js:2:16)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)

**Comment by endel** [comment]
Hey @takaaptech!

Maybe your node version doesn't support the new ES6 features, which version are you using? It should work fine on v4+

```
$ node --version
v5.0.0
```

**Comment by takaaptech** [comment]
Ah ok after update node to 5.0, npm start works, but node index.js does not work, here is the logs, maybe you can fix it.. Thank so much!
$ node --version
v5.0.0
$ npm start

> colyseus-lua-example@1.0.0 start colyseus.lua-master/server
> node --harmony index.js

Listening on http://localhost:2657
^C
$ node index.js 
colyseus.lua-master/server/chat_room.js:3
class ChatRoom extends Room {
^^^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:404:25)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (colyseus.lua-master/server/index.js:2:16)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
$

**Comment by endel** [comment]
Hey @takaaptech,

Actually as the server uses JavaScript ES6 features we should always start node with the `harmony` flag, like this:

```
$ node --harmony index.js
```

Hope this helps! Please do share your experiences about using this, I'd like to make it as easy as possible to create multiplayer games.

**Comment by takaaptech** [comment]
Hi @endel,
Thank so much for your help and your awesome framework! I will using it for my turn base game logic now. I will ask you help many many more :)
